"""add_temporizadores

Revision ID: 62ef78e6cad6
Revises: 6a097c70be35
Create Date: 2026-04-30 22:08:44.213618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62ef78e6cad6'
down_revision: Union[str, Sequence[str], None] = '6a097c70be35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('temporizadores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paso_receta_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('duracion_segundos', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=15), nullable=False),
    sa.Column('fecha_inicio', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fecha_confirmacion', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('duracion_segundos > 0', name='chk_temporizadores_duracion_positiva'),
    sa.CheckConstraint("estado IN ('inactivo', 'corriendo', 'pausado', 'completado')", name='chk_temporizadores_estado_valido'),
    sa.ForeignKeyConstraint(['paso_receta_id'], ['pasos_receta.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_temporizador_usuario_estado', 'temporizadores', ['usuario_id', 'estado'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_temporizador_usuario_estado', table_name='temporizadores')
    op.drop_table('temporizadores')
    # ### end Alembic commands ###
