"""add_pedidos

Revision ID: 6a097c70be35
Revises: c778a5f8946d
Create Date: 2026-04-24 21:02:15.008618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a097c70be35'
down_revision: Union[str, Sequence[str], None] = 'c778a5f8946d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('cliente_nombre', sa.String(length=150), nullable=False),
    sa.Column('cliente_whatsapp', sa.String(length=20), nullable=True),
    sa.Column('fecha_entrega', sa.DateTime(timezone=True), nullable=False),
    sa.Column('punto_entrega', sa.String(length=255), nullable=True),
    sa.Column('estado', sa.String(length=25), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("estado IN ('pendiente', 'en_preparacion', 'listo', 'entregado', 'cancelado')", name='chk_estado_pedido'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pedidos_usuario_fecha', 'pedidos', ['usuario_id', 'fecha_entrega'], unique=False)
    op.create_table('lineas_pedido',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('receta_id', sa.UUID(), nullable=True),
    sa.Column('nombre_producto', sa.String(length=200), nullable=False),
    sa.Column('cantidad_porciones', sa.Integer(), nullable=False),
    sa.Column('precio_acordado_mxn', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('cantidad_porciones > 0', name='chk_cantidad_porciones'),
    sa.CheckConstraint('precio_acordado_mxn >= 0', name='chk_precio_acordado'),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lineas_pedido_pedido_id'), 'lineas_pedido', ['pedido_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lineas_pedido_pedido_id'), table_name='lineas_pedido')
    op.drop_table('lineas_pedido')
    op.drop_index('ix_pedidos_usuario_fecha', table_name='pedidos')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
