"""init_database_models

Revision ID: 9dbbbf5a0e50
Revises: 
Create Date: 2026-04-12 13:55:08.548468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dbbbf5a0e50'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('insumos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('unidad', sa.String(length=10), nullable=False),
    sa.Column('precio_compra', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad_comprada', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('cantidad_actual', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('alerta_minimo', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('fecha_ultimo_precio', sa.Date(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insumos_usuario_id'), 'insumos', ['usuario_id'], unique=False)
    op.create_table('movimientos_insumo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('insumo_id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('cantidad', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('motivo', sa.String(length=30), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movimientos_insumo_insumo_id'), 'movimientos_insumo', ['insumo_id'], unique=False)
    # ### end Alembic commands ###
    # Índice compuesto para optimizar GET /insumos?activo=true filtrado por usuario
    op.create_index('ix_insumos_usuario_activo', 'insumos', ['usuario_id', 'activo'])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_insumo_insumo_id'), table_name='movimientos_insumo')
    op.drop_table('movimientos_insumo')
    op.drop_index(op.f('ix_insumos_usuario_id'), table_name='insumos')
    op.drop_table('insumos')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
    op.drop_index('ix_insumos_usuario_activo', table_name='insumos')
