"""add_recetas_costeo_tiempos

Revision ID: c778a5f8946d
Revises: 9dbbbf5a0e50
Create Date: 2026-04-14 11:55:52.008471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c778a5f8946d'
down_revision: Union[str, Sequence[str], None] = '9dbbbf5a0e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recetas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('porciones', sa.Integer(), nullable=False),
    sa.Column('margen_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('fecha_modificacion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recetas_usuario_id'), 'recetas', ['usuario_id'], unique=False)
    op.create_table('gastos_ocultos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('receta_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('es_porcentaje', sa.Boolean(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ingredientes_receta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receta_id', sa.UUID(), nullable=False),
    sa.Column('insumo_id', sa.UUID(), nullable=False),
    sa.Column('cantidad_usada', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('unidad', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receta_id', 'insumo_id', name='uix_receta_insumo')
    )
    op.create_table('pasos_receta',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('receta_id', sa.UUID(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('duracion_segundos', sa.Integer(), nullable=True),
    sa.Column('es_critico', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['receta_id'], ['recetas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('receta_id', 'orden', name='uix_receta_orden_paso')
    )
    op.drop_index(op.f('ix_insumos_usuario_activo'), table_name='insumos')
    # ### end Alembic commands ###
    op.create_index('ix_recetas_usuario_activa', 'recetas', ['usuario_id', 'activa'])
    op.create_index('ix_gastos_usuario_receta_tipo', 'gastos_ocultos', ['usuario_id', 'receta_id', 'tipo'])

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Eliminar índices compuestos
    op.drop_index('ix_gastos_usuario_receta_tipo', table_name='gastos_ocultos')
    op.drop_index('ix_recetas_usuario_activa', table_name='recetas')
    op.create_index(op.f('ix_insumos_usuario_activo'), 'insumos', ['usuario_id', 'activo'], unique=False)
    op.drop_table('pasos_receta')
    op.drop_table('ingredientes_receta')
    op.drop_table('gastos_ocultos')
    op.drop_index(op.f('ix_recetas_usuario_id'), table_name='recetas')
    op.drop_table('recetas')
    # ### end Alembic commands ###
