"""add_notificaciones_programadas

Revision ID: f42991c44300
Revises: 62ef78e6cad6
Create Date: 2026-05-05 18:58:07.483587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f42991c44300'
down_revision: Union[str, Sequence[str], None] = '62ef78e6cad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notificaciones_programadas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=True),
    sa.Column('insumo_id', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('fecha_programada', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enviada', sa.Boolean(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("tipo IN ('recordatorio_entrega', 'alerta_desabasto', 'margen_en_riesgo')", name='check_tipo_notificacion'),
    sa.CheckConstraint('pedido_id IS NOT NULL OR insumo_id IS NOT NULL', name='check_entidad_referenciada'),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notif_enviada_fecha', 'notificaciones_programadas', ['enviada', 'fecha_programada'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notif_enviada_fecha', table_name='notificaciones_programadas')
    op.drop_table('notificaciones_programadas')
    # ### end Alembic commands ###
