"""add_user_plan_gastos_default

Revision ID: f60acb49228d
Revises: f42991c44300
Create Date: 2026-05-15 21:36:36.774597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f60acb49228d'
down_revision: Union[str, Sequence[str], None] = 'f42991c44300'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plan', sa.String(length=20), nullable=False, server_default='free'))
    op.add_column('users', sa.Column('empaque_mxn_default', sa.Numeric(precision=10, scale=2), nullable=True, server_default='0.00'))
    op.add_column('users', sa.Column('desgaste_pct_default', sa.Numeric(precision=5, scale=2), nullable=True, server_default='0.00'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'desgaste_pct_default')
    op.drop_column('users', 'empaque_mxn_default')
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
